### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by cannc4** [evshiron/nwjs-builder-phoenix#21]
Hi, sorry for the non-issue posting but I have an app that communicates with a sound engine (SuperCollider) running in localhost, alongside with a Haskell compiler. They are all wrapped in a react-app with related `package.json` format. 

I am a bit confused about the compatibility and my search led me here, which seem to be the latest updated repo of nw.js

I'd appreciate any help
cheers

**Comment by evshiron** [comment]
Could you describe your question again so that I know what to answer? What compatibility are you worrying about?

These SuperCollider and Haskell compiler look like native applications, if you are running across operating systems I am afraid some extra work is needed to get them working, for example bundling binaries for different platforms, or use `wine` to launch Windows binaries on other platforms.

JavaScript modules without native bindings should work across platforms because NW.js takes care of low-level API differences. If modules with native bindings a.k.a. native addons, you will need to compile for different platforms, see [Use Native Node Modules](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/) for instructions.

**Comment by cannc4** [comment]
Thanks for your prompt answer :) 

I'll test it and report back with a more detailed question

**Comment by cannc4** [comment]
So I tried to run it with the following `package.json`
https://gist.github.com/cannc4/fd877846ff7e7cca0c5630a53b8ed40e

When I write `localhost` instead of `index.html` for the main route, I get a partial amount of the interface, otherwise nothing except the title.

I also can't see the dev tools and toolbar - so I can not really debug what's going on.
Here is the repo I am testing it with:
https://github.com/cannc4/siren

Any clues?

**Comment by evshiron** [comment]
Hmm. I have cloned your repo and managed to make it run in NW.js (that `login.gif` took me quite a long time to download). Here's the steps:

* Install `nwjs-builder-phoenix` and make it `devDependency`
  * `npm install nwjs-builder-phoenix --save-dev`
* Add the following properties in `package.json`:

```json
{
  "main": "http://localhost:3000",
  "scripts": {
    "startnw": "run ."
  },
  "build": {
    "nwVersion": "latest"
  }
}
```

* Run `npm start` and `npm run siren`
* Run `npm run startnw`
  * A window should show up and display correctly

Notes:

* Most properties in your gist are not necessary, read NW.js docs and `nwjs-builder-phoenix` docs for reference.
* You are using `Object.values` which is supported in Chromium 54, while NW.js 0.14.7 (the LTS version) uses Chromium 50, and as a result errors happened. Use versions later instead.
* When using the `run` command, the app always runs with NW.js SDK flavor, which has DevTools and allow browser-like debugging. However in your app the context menu doesn't work, and you will have to access DevTools via keyboard shortcuts, which should be described in NW.js docs (in macOS I can open DevTools via Window > Devtools).
* I have no idea how to pack your app because it uses a remote entry point. In general, you want to run `npm run build` to make a production build of your app, set the entry point to `index.html`, ignore other files and pack. Some options like `node-remote` might also be set.
  * In my opinion, what you need is to serve the production build of your app via backend, start the backend in NW.js, and open a new window accessing the remote entry point.

Hope it helps.

**Comment by cannc4** [comment]
Hi, thanks for your in-depth reply. It works now with the pre-build setup.

I was actually trying with the built version of it and somehow failed at it when pointing the main to `index.html` as it was not showing up properly in the NW.js. I'll consider and have a think about what you mentioned.

thanks a lot for your help
