### ISSUE TITLE
IDEA: Integrate ASAR format

### ISSUE THREAD

**Issue by matthew-dean** [evshiron/nwjs-builder-phoenix#23]
First: thanks for taking this on! Building / updating NW.js apps is still a HUGE challenge.

One thing I was thinking nw-builder could add is ASAR support. Although it was built for Electron, there's no reason it couldn't be used for NW.js! See: https://www.npmjs.com/package/asar-fs https://www.npmjs.com/package/asar.

That could make installation / updates a lot faster since there's only one (or almost one) file to remove / add as far as the web app.

**Comment by evshiron** [comment]
Thank you and thanks for the suggestion.

Support for `.asar` is not ideal.

How would `nwjs-builder-phoenix` support `.asar`?

As `.asar` support isn't in NW.js runtime, to provide access to `app.asar`, we will need to take over the entry point to monkey patch functions before real app launches. And currently `asar-fs` won't work with `childProcess.spawn` or (possibly) native addons. Which will make users confused if they aren't aware of it.

`.asar` is an excellent replacement to `.zip` (a.k.a `.nw`), and it has well-known caveats and corresponded workarounds, while `asar-fs` not (and has far less users).

If a user already uses `asar-fs` in the app, `nwjs-builder-phoenix` can build for it using existing methods. I don't want to create/force a way to write NW.js apps and I think the better way to provide `.asar` support is in NW.js runtime, and share the same caveats and workarounds with Electron.

I agree that the more small files there are, the slower the installation will be. I use `webpack` to bundle most modules and ignore the original files by making them `devDependencies`, so that only `dependencies` will be copied, and ignore loose files (like examples) with specified naming patterns. I have to admit that it doesn't solve the problem though.

Currently the updater works by removing/writing files according to the difference between old and new versions. If we use a single `.asar`, we will be using VPatch to apply the differences.

As a result, I am not adding this feature at the moment, but if you are interested a PR is always appreciated.

**Comment by matthew-dean** [comment]
Okay, I haven't tried the updater yet, I'll check it out!

And fair points about ASAR limitations. I'm just finding that the re-installation process takes a long time just by the number of files. Do you mean to say that you are bundling node_modules using webpack? Hmm I've never considered this.

**Comment by evshiron** [comment]
That auto updater was released earlier this day, please try it out and give some feedbacks :)

That VPatch shouldn't be difficult to integrate, but until there is a must I will leave it aside.

Yes, as far as I am a user of TypeScript and React, it will be a hard time if I don't use `webpack`. Most `node_modules` can be bundled as long as they don't use native addons. I have described this in [FAQs](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/docs/FAQs.md), feel free to check it out.

`webpack` will still need some tweaking to further reduce the size and accelerate building speed, for example, to uglify via `webpack -p`, configure `externals` and use minified files instead of bundling them every time.
