### ISSUE TITLE
mac icon file ignored

### ISSUE THREAD

**Issue by SteveBrooker** [evshiron/nwjs-builder-phoenix#24]
I added first "icon":"app.icns" and later "icon":"app" in the mac object in the package.json file and neither of these worked, with the resulting build always keeping the default nw icon. I tried putting the app.icns file in both the app root folder and in the src/ sub folder and in both. None of these worked.

Also I cannot seem to get the dist folder to appear under the root app folder. I tried specifying output as "dist/" and ./dist/"

But I am pleased in one regard because I have a normal flavour build for the first time whereas nw-builder always gives me an sdk build whatever I do.

**Comment by evshiron** [comment]
Greetings.

Paths in `nwjs-builder-phoenix` options are always relative to the project root where `package.json` is, otherwise an absolute path should be used. By the way, have you received any `ENOENT` errors?

I have refactored the code to avoid ambiguous results, and updated the sample project, whose icon and the output directory works as expected.

Could you build the sample project and see if it's working? Here's the steps:

```bash
git clone https://github.com/evshiron/nwjs-builder-phoenix
cd ./nwjs-builder-phoenix/assets/project/
npm install
# Remove or change `--mirror https://npm.taobao.org/mirrors/nwjs/` of `npm run build` if you experience a slow download speed.
# vi package.json
npm run build
```

It will be great if there will be logs attached.

**Comment by SteveBrooker** [comment]
Thanks
I build your example project and the icon was correct
Examining the differences between your example project and mine, the only difference was that all of my html/js/css was in a folder src/ and my build script specified this folder rather than .
When I moved everything out of src into the main folder everything worked fine and the icon was correct.
However I would like to be able to keep my code in a sub folder of the project and I am not sure how to do this correctly to ensure the build process finds the icon.

**Comment by evshiron** [comment]
The options will be read from the `package.json` of the specified directory. That's to say, if you `build .`, options from `./package.json` will be used; if you `build ./src/`, options will be read from `./src/package.json`.

That specified directory will also become the current working directory from which we find and copy files.

Assuming `//` is the project root,
if you set `build.mac.icon` to `./assets/icon.icns` in `//package.json`
and then run `build //src/`,
options will be read from `//src/package.json` rather than `//package.json`.
If `//src/package.json` isn't configured to modify icons, icons will remain unchanged.
If `//src/package.json` also has `build.mac.icon` set to `./assets/icon.icns`, `//src/assets/icon.icns` will be used (if it doesn't exist, error is thrown).

So there are two ways:

* `build .`, configure options in `//package.json`, and ignore other files if needed.
* `build ./src/`, configure options in `//src/package.json`, the outcome will be in `//src/dist/` by default.

If it's only the icon that is anonying you, you can set `build.mac.icon` to an absolute path to the icon file, which should work too.

The above usage is tested in [/test/Builder.js](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/test/Builder.js).

**Comment by SteveBrooker** [comment]
Thanks evshiron for a very clear explanation. You can close this issue as far as I am concerned.

**Comment by evshiron** [comment]
You are welcome. If there is any issue, let me know :)

**Comment by SteveBrooker** [comment]
Evshiron

Built my app for mac working fine. Trying now to do the same for windows and Linux

added —win to the script. Did not add a separate object build.win as happy to accept defaults for now (is this my mistake?)

Anyway, this is what happened (bash log below) and I do not know where to go from here. 

All help very gratefully received.

Steve

> build --mac --win --x64 .

Starting building tasks... { tasks: [ [ 'win', 'x64' ], [ 'mac', 'x64' ] ],
  concurrent: false }
Fetching NW.js binary... { platform: 'win', arch: 'x64', version: 'lts', flavor: 'normal' }

[==================================================] 378.64KB/s 1.2s

Building targets...
{ Error: spawn wine ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: 
   [ '/Users/steve/Documents/INTBOX PROJECTS/TEAMMAP/NWJS APPS/TM DESKTOP/node_modules/rcedit/bin/rcedit.exe',
     '/Users/steve/Documents/INTBOX PROJECTS/TEAMMAP/NWJS APPS/TM DESKTOP/dist/TeamMap-0.62.70.1-win-x64/nw.exe',
     '--set-version-string',
     'ProductName',
     'TeamMap',
     '--set-version-string',
     'FileDescription',
     'teammap',
     '--set-file-version',
     '0.62.70.1',
     '--set-product-version',
     '0.62.70.1' ] }

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prod"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! TeamMap@0.62.7-0.1 prod: `build --mac --win --x64 .`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the TeamMap@0.62.7-0.1 prod script 'build --mac --win --x64 .
Steve Brooker
e:  steve.brooker@intbox.co.uk
m: +44 (0)7790 491197
p:  +44 (0)1980 505262

**Comment by evshiron** [comment]
`nwjs-builder-phoenix` requires `wine` to generate Windows builds from macOS or Linux. For macOS, `brew install wine` should be the easiest way. If you have installed `wine` before, make sure `wine` is in the `PATH`.

**Comment by SteveBrooker** [comment]
Evshiron
Thanks, I will give it a go.
Steve Brooker
e:  steve.brooker@intbox.co.uk
m: +44 (0)7790 491197
p:  +44 (0)1980 505262

**Comment by SteveBrooker** [comment]
Evshiron

I installed wine at it all worked. Thank you.
Any progress on Linux builds? 

Steve Brooker
e:  steve.brooker@intbox.co.uk
m: +44 (0)7790 491197
p:  +44 (0)1980 505262

**Comment by evshiron** [comment]
No idea, they should work though. If you find anything doesn't work or want to request some new features, feel free to tell.

**Comment by SteveBrooker** [comment]
Evshiron

I asked you about whether Linux builds would work, because

a) your GitHub page marks Linux as TODO, and
b) there is no information on the options page regarding what to set in your build.linux
c) your example does not include Linux.

Linux is not a priority market for my app, I was just wondering when... 

Steve Brooker
e:  steve.brooker@intbox.co.uk
m: +44 (0)7790 491197
p:  +44 (0)1980 505262

**Comment by evshiron** [comment]
That TODO means Linux-specified features, for example, specifying icons by `.desktop`, and packaging apps in `.deb` or something for distribution. Common targets like `.zip` and `.7z` are available for all these platforms, including Linux.

The reason why it's a "TODO" is that Linux is fragmented. It will be difficult for me to support all these target formats (supported by `electron-builder`) like AppImage, snap, `.deb`, `.rpm` and others all on my own, not to mention that I don't have these various platforms to test them out.

Linux users are smart, and they (should) know how to use it when they receive an Linux app in `.zip` or `.tar.gz` formats, which I thought was enough. I'm not a Linux user at the moment and don't know what's needed for Linux apps. It will be appreciated if someone helps out with feature requests and hopefully PRs.

**Comment by SteveBrooker** [comment]
Evshiron
Thanks for the answer.
I will try a Linux build and see how it goes.

Steve Brooker
e:  steve.brooker@intbox.co.uk
m: +44 (0)7790 491197
p:  +44 (0)1980 505262
